# Project-wide settings — fill in as pipeline takes shape
raw_data:
  raw_scraped: ../data/raw/goodreads.csv
  raw_api: ../data/raw/google_books.csv
  raw_concatenated: ../data/raw/combined_books.csv
  raw_combined: ../data/raw/all_books.csv
clean_data:
  clean: ../data/clean/booksDB.csv
  clean_st: ../data/clean/streamlitcatalog.csv